apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: $appname
  labels:
    app: $appname
spec:
  selector:
    matchLabels:
      app: $appname
  replicas: 1
  template:
    metadata:
      labels:
        app: $appname
    spec:
      containers:
      - name: $appname
        image: $TARGETREPO/$appname
        imagePullPolicy: Always
        ports:
        - containerPort: 9080       
---
apiVersion: v1        
kind: Service
metadata:
  name: $appname
  labels:
    app: $appname
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9080
  selector:
   app: $appname
